### ISSUE TITLE
Default the `live` subcommand to showing annotations

### ISSUE THREAD

**Issue by PeterJCLaw** [WillB97/april_vision#10]
As it stands the `live` subcommand in its default behaviour isn't massively useful. I did find the `--annotate` option, however initially I thought there was something wrong with my setup (camera or marker) when it wasn't finding the marker I was showing it.

I would also encourage having the CLI print out info about the markers it's seeing. Here's what I've got for that locally:
``` python
        if markers:
            print(f"Found {len(markers)} makers:")

            for marker in markers:
                print(f" #{marker.id}")
                print(f" {marker.pixel_corners=}")
                print(f" {marker.spherical=}")
                print(f" {marker.cartesian=}")
                print(f" {marker.orientation=}")
                print()

            print()
            print(" --- ")
            print()
```

**Comment by 8BitJosh** [comment]
I will create a change to invert the behaviour of `--annotate` 

I was originally going to impliment a feature to print the results to the terminal but my main concern was the quantity of data. If your webcam is running at 30fps and there are a few markers that is a few hundred lines per second. 

We could potentially extend the opencv `waitKey` functionality to print to terminal on a key press but I am open to ideas

**Comment by PeterJCLaw** [comment]
> I was originally going to impliment a feature to print the results to the terminal but my main concern was the quantity of data.

One option might be to only print the details for the first marker and then emit a "more markers' details not printed" message. Combining that with a `--print-details=N` flag (default `N=1`) would allow the user to opt to have more markers details printed if that's what they want. (`N=0` would disable printing; negative values or maybe `N='all' prints an unlimited number)

Thoughts?

> If your webcam is running at 30fps and there are a few markers that is a few hundred lines per second.

A way to limit the fps might be neat too -- for the case of debugging the orientation stuff, 2 fps is plenty.
