### ISSUE TITLE
ci: Virtual Environment is not cached

### ISSUE THREAD

**Issue by trickeydan** [WillB97/april_vision#3]
We can improve the speed of the CI setup using a lock file (#2) and then caching the virtual environment.

When the lock file is changed, we can then invalidate the cached environment.

For examples of this, see other SR projects, e.g astoria

https://github.com/srobo/astoria/blob/3ede4e4decac4be8b3d7a5fafece00852a2ce0eb/.github/workflows/tests.yml#L28-L31

**Comment by WillB97** [comment]
Installing dependencies only takes a handful of seconds and means that the install is the same as a production install.
