### ISSUE TITLE
`SphericalCoordinate` type incompatibl with Zoloto

### ISSUE THREAD

**Issue by PeterJCLaw** [WillB97/april_vision#8]
In legacy mode, spherical coordinates have the following incompatible differences than Zoloto:
- the distance member is called `distance` where Zoloto called this member `dist`
- the tuple unpacking of the type is `(distance, theta, phi)` where Zoloto used `(rot_x, rot_y, dist)`, which is incompatible (especially since `theta` and `phi` have very different meanings than `rot_x` and `rot_y`

**Comment by WillB97** [comment]
This implementation is taken from the version of Zoloto in the [v2023.1.0](https://github.com/srobo/robot-image/tree/v2023.1.0) image, release on Dec 1st.
https://github.com/srobo/zoloto/blob/master/zoloto/coords.py#L87

**Comment by PeterJCLaw** [comment]
This ship has sailed.
